// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnwxqEw0z3qUl95lP6CJgVaFNWgdFYbI',
    appId: '1:654292963388:web:1eb4997420b247c054f339',
    messagingSenderId: '654292963388',
    projectId: 'healthblox',
    authDomain: 'healthblox.firebaseapp.com',
    storageBucket: 'healthblox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ML1H500irSKK2xd51oct6h-6vdE9k8I',
    appId: '1:654292963388:android:7961d58aa085c21d54f339',
    messagingSenderId: '654292963388',
    projectId: 'healthblox',
    storageBucket: 'healthblox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVSAknfWqHWCL8Bl1ez46L0zGGXoLIoPI',
    appId: '1:654292963388:ios:f84abdccaf58361454f339',
    messagingSenderId: '654292963388',
    projectId: 'healthblox',
    storageBucket: 'healthblox.appspot.com',
    iosClientId: '654292963388-jhemj5u5heu4t2noge680q512pmcmt8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthblox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVSAknfWqHWCL8Bl1ez46L0zGGXoLIoPI',
    appId: '1:654292963388:ios:f84abdccaf58361454f339',
    messagingSenderId: '654292963388',
    projectId: 'healthblox',
    storageBucket: 'healthblox.appspot.com',
    iosClientId: '654292963388-jhemj5u5heu4t2noge680q512pmcmt8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthblox',
  );
}
